### ISSUE TITLE
Joint creation example for documentation

### ISSUE THREAD

**Issue by cadop** [yanshil/Fusion2PyBullet#10]
The project looks really great and useful, but it's a bit hard to understand how to setup the joints in fusion to make it work. As someone that does use fusion regularly, it is still unclear to me how to name or set up joints.  Is a walkthrough available somewhere, or could something be worked on?

**Comment by yanshil** [comment]
I would recommend you go through the tutorial in https://help.autodesk.com/view/fusion360/ENU/courses/
Especially the "Mechanical assemblies" section.
