### ISSUE TITLE
Joint location issue

### ISSUE THREAD

**Issue by unitbob1** [yanshil/Fusion2PyBullet#11]
Hi there,

I am having what seems to be the same joint location calculation issue that was previously fixed. I am using the latest code and the latest fusion. I can successfully create a URDF file, but when placed in a viewer / pybullet the rotation of the joints is incorrect. I have attatched the URDF file that I have generated, and can also provide the fusion file if neccessary.

Thanks
[Assembly_urdf_modded.zip](https://github.com/yanshil/Fusion2PyBullet/files/7049224/Assembly_urdf_modded.zip)

**Comment by DanielSioldea** [comment]
Hey @unitbob1, did you ever find a solution to this issue? I might be having the same problem.

**Comment by risuke777** [comment]
@BoofinBool @unitbob1 
Hi! I might had the same problem. I solved this by recreating component.

In Fusion
1．move the component(call component.A) to desired position (ex. by using joint)
2．copy the body in component.A to the root body file(call body.A) (Ct+C and Ctl+V)
3．remove component.A and create a component(call component.B) from body.A
4．then apply rotation joint to component.B

I assume component position should be in desired postion before using rotation joint.
