### ISSUE TITLE
Units does not scale

### ISSUE THREAD

**Issue by Ugo31** [yanshil/Fusion2PyBullet#2]
That's a really nice tool you made, I am sad I just discovered it!

However, I found a small issue or maybe I've missed something :

In Fusion 360 if the document settings are in anything other than _mm_ , the URDF model will not scale.
For example if I use _cm_ as default units in Fusion then the URDF model will be 1/10 the size of the original.
Not a huge deal just good to know.

Thanks again for your work!

**Comment by yanshil** [comment]
Yeah you are right. That's because STL file doesn't actually include units information.

I should have write this down in the README but I forgot that.

---

Here is a solution to export correct size:

Check `Bullet_URDF_Exporter/core/Link.py`

By modifying the `'scale':'0.001 0.001 0.001'` to a **proper value** will scale it to the size you want.

```
        # visual
        visual = SubElement(link, 'visual')
        origin_v = SubElement(visual, 'origin')
        origin_v.attrib = {'xyz':' '.join([str(_) for _ in self.xyz]), 'rpy':'0 0 0'}
        geometry_v = SubElement(visual, 'geometry')
        mesh_v = SubElement(geometry_v, 'mesh')
        mesh_v.attrib = {'filename': self.repo + self.name + '.stl','scale':'0.001 0.001 0.001'}
        material = SubElement(visual, 'material')
        material.attrib = {'name':'silver'}
        
        # collision
        collision = SubElement(link, 'collision')
        origin_c = SubElement(collision, 'origin')
        origin_c.attrib = {'xyz':' '.join([str(_) for _ in self.xyz]), 'rpy':'0 0 0'}
        geometry_c = SubElement(collision, 'geometry')
        mesh_c = SubElement(geometry_c, 'mesh')
        mesh_c.attrib = {'filename': self.repo + self.name + '.stl','scale':'0.001 0.001 0.001'}
```
