### ISSUE TITLE
Issues with Joint.make_joints_dict

### ISSUE THREAD

**Issue by nyxaria** [yanshil/Fusion2PyBullet#3]
Hello, I am having the following problem:

Before Running:
![image](https://user-images.githubusercontent.com/9167240/91219661-e4117b80-e712-11ea-916b-7f446c6d2897.png)
<br>
After Running:
![image](https://user-images.githubusercontent.com/9167240/91219574-be847200-e712-11ea-922d-f37862a04987.png)

On the side, you can see the joints go yellow when I run the script. Could this be a reason? Some of the joints were created with the "As-built joint" which results in a rigid joint.

I tried debugging it myself:

str(root.joints):
![image](https://user-images.githubusercontent.com/9167240/91219990-69952b80-e713-11ea-9b50-e87df583a18d.png)

str(root.joints[0])
![image](https://user-images.githubusercontent.com/9167240/91220095-8fbacb80-e713-11ea-841f-13a72eff05cc.png)

But I can't print with ui.messageBox inside the Joint.py file, even if I pass in `ui`

**Comment by nyxaria** [comment]
I think the problem is the "As-built joint", do you agree?

**Comment by nyxaria** [comment]
I removed the As-build joints, and it works! The problem is that As-build joints don't have an origin.

**Comment by nyxaria** [comment]
I tried a minimal example with only 2 revolute joints and it works, but as soon as I try to generate URDF in the assembly which contains the minimal example it fails

**Comment by nyxaria** [comment]
I found the problem, none of the components can be linked. You have to right click on all components and select "Break link" otherwise the script can't rename the components and throws an error

**Comment by nyxaria** [comment]
Sorry for so much spam -- the problem was that the error was being thrown inside traverseAssembly, and the error message was really not good and didn't tell me what is wrong. I will make a pull request with better messages.

**Comment by yanshil** [comment]
LOL yeah
1. Yes, as-build-joint is not supported. I listed supported joint types but didn't implicitly point out that as-built joint is not supported
2. The error message...indeed can tell nothing! I also found this problem but I don't have time to solve it elegantly. So if you could make it better I will really appreciate it XD
