### ISSUE TITLE
get same old error like fusion2urdf

### ISSUE THREAD

**Issue by stardobas** [yanshil/Fusion2PyBullet#4]
I have follow instruction but get same error index-1 out of range...
using  fusion2urdf, my project is perfect generated...

**Comment by yanshil** [comment]
Did you try this: https://github.com/yanshil/Joint2Graphviz to take a look at your nested component structure?

**Comment by yanshil** [comment]
OK I think I got what you mean. Fusion updated it's API. I‘ll fix that

**Comment by yanshil** [comment]
Updated.
