### ISSUE TITLE
Joints being rotated 90degrees

### ISSUE THREAD

**Issue by jakubmatyszczak** [yanshil/Fusion2PyBullet#5]
Hi i have used your plugin in the past with great success but now (supposetly after latest F360 update) joints are rotated by 90 degrees in the same direction.  Please refer to the images below. I deduct the issue is somehow related on fusion2urdf plugin that your plugin is based on since i've got similar results while using the other one.
![pre](https://user-images.githubusercontent.com/71089406/99807887-64901e80-2b40-11eb-8f04-3c368b534b50.PNG)
![post](https://user-images.githubusercontent.com/71089406/99807866-5fcb6a80-2b40-11eb-9191-2f7477dd86ff.PNG)

[EDIT] I will just add that i've also tried without adding assemblies, just every single part imported to the design and joined to the base link. I'am almost sure my joints are set correctly (as i said, I've used the plugin in the past) and i've also doublechecked them with Joint2Grphviz.

**Comment by yanshil** [comment]
I might not have time to fix it these few weeks. Could you share a failure example here so that I can test it while I have time?
