### ISSUE TITLE
error with the connections between old_component1 and servo_v11

### ISSUE THREAD

**Issue by VibhanshuV** [yanshil/Fusion2PyBullet#9]
I am trying to export my biped robot from fusion but I get the following error:

Joint Rigid5: There seems to be an error with the connection between
old_component1
and
servo_v11

Check whether the connections
parent=component2=old_component1
child=cpmponent1=servo_v11
are correct or if you need to swap component1<=>component2

I can't seem to find any error between the connections in the model. Also, I checked the design with Joint2Graphviz, and evrrything looks fine.

**Comment by yanshil** [comment]
Could you please attach your Joint2Graphviz result?

(I have no idea what happens with the model while I can't reproduce the error. But I'll try my best to help with that.

**Comment by VibhanshuV** [comment]
I have attached the Joint2Graphviz result (which seems as required),  the error that I am getting, and my assembly. Please help. 

[Joint2Graphviz_Biped.txt](https://github.com/yanshil/Fusion2PyBullet/files/6200123/Joint2Graphviz_Biped.txt)
![error_fusion2pybullet](https://user-images.githubusercontent.com/65086796/112375181-fedbbb00-8d08-11eb-979a-3794576b9f4c.png)


[Biped Assembly.zip](https://github.com/yanshil/Fusion2PyBullet/files/6200129/Biped.Assembly.zip)

**Comment by yanshil** [comment]
Your root node has to be named as `base_link` 

----
Oh, I saw your graphviz result with the base_link
I will play with your file and response later

**Comment by yanshil** [comment]
Hey, I think I found the problem.

Please select all the components, right click and 'Break Link'. Then this script will works.

It cannot deal with some modifications on the components with extra file links.
